# Generated by Django 5.0.3 on 2024-03-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_pdfdocument_delete_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('cover_image', models.ImageField(upload_to='covers/')),
                ('pdf_file', models.FileField(upload_to='pdfs/')),
            ],
        ),
        migrations.DeleteModel(
            name='PDFDocument',
        ),
    ]
