# Generated by Django 5.0.3 on 2024-03-31 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
