# Generated by Django 5.0.3 on 2024-03-31 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
