# Generated by Django 5.0.3 on 2024-04-04 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_book_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
        migrations.DeleteModel(
            name='SearchResult',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
